### ISSUE TITLE
/coll_open.png not found

### ISSUE THREAD

**Issue by danrabbit** [elementary/valadoc-org#31]
keep getting an error about it's trying to find /coll_open.png, which is now at /images/coll_open.png. I can't figure out where this is

**Comment by btkostner** [comment]
It seems to be hard coded in valadoc

**Comment by lewisgoddard** [comment]
Yay! Hard-coded references!

**Comment by benwaffle** [comment]
Fixed if you use [our valadoc fork](https://github.com/elementary/valadoc)
